[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/function-1"
  to = "https://us-central1-arch-lambda-htech.cloudfunctions.net/function-1"
  status = 200